<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HelloHamburger.Core\HelloHamburger.Core.csproj" />
    <ProjectReference Include="..\HelloHamburger.DataAccess\HelloHamburger.DataAccess.csproj" />
    <ProjectReference Include="..\HelloHamburger.Entities\HelloHamburger.Entities.csproj" />
  </ItemGroup>

</Project>
